Repository DevF3st/Learn-Programming, pull requests merged in 2023-10, with the labels that each got.

#43 Prime Numbers
  .vscode/launch.json
  .vscode/tasks.json
  C#/EvenNumbers.cs
  C++/EvenNumbers.cpp
  C/PrimeNumbers.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#52 Fibonacci Recursive using Java
  Java/FibonacciRecursive.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#53 Fibonacci code ♾ in Go programming language
  GoLang/Fibonacci algorithm ♾ in Go programming language
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#56 Create binary_search.cpp
  C++/binary_search.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#57 Create BST.cpp
  C++/BST.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#42 Create AllSearchingAlgorithm.cpp
  C++/AllSearchingAlgorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#65 Odd Numbers C++
  C++/OddNumbers.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#60 Added fibonacci script in python
  Python/Fibonacci.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#61 Create fibonacci.php
  PHP/fibonacci.php
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#63 Create PaddleBall.py
  Python/games/PaddleBall.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#64 added fibonacci algorithm in c language
  C/FibonacciAlgorithm.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#66 Fibonacci Series.cpp
  C++/Fibonacci Series.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#67 Create fibonacci.cs
  C#/fibonacci.cs
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#68 Create fibonacci.cpp
  C++/fibonacci.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#69 Create fibonacci.js
  JavaScript/fibonacci.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#70 Added Fibonacci Series in C++
  C++/fibonacciSeries.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#71 Create Dfs.cpp
  C++/Dfs.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#73 Create Search_in_sorted_array.cpp
  C++/Search_in_sorted_array.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#74 Fibonacci Series in C lang
  C/Fibonacci.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#72 Create dfs.cpp
  C++/dfs.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#75 Trapping Rainwater Problem
  Java/trapping_rainwater_problem.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#76 Kadane's Algorithm
  Java/Kadane's_Algorithm.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#78 HeapSort Added in Python
  Python/HeapSort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#80 Create mergeSort.java
  Java/mergeSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#81 Create StringToByte.java
  Java/StringToByte.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#82 issue#46
  Python/fibonnaci_sequence.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#83 Fibbonacci series added in C++
  C++/Fibonacciseries.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#84 Create SelectionSort.java
  SelectionSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#85 Create BubbleSort.java
  BubbleSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#86 Create InsertionSort.java
  InsertionSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#87 Create MergeSort.java
  MergeSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm

#88 Create quickSort.java
  quickSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023, algorithm
